services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  db-auth:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: authdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql_auth

  db-orchestrator:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: orchestratordb
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql_orchestrator

  db-user:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: userdb
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql_user

  db-model:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: modeldb
    ports:
      - "5436:5432"
    volumes:
      - pgdata:/var/lib/postgresql_model

volumes:
  pgdata: